### ISSUE TITLE
Regression in SAM class

### ISSUE THREAD

**Issue by zamaudio** [ssadedin/groovy-ngs-utils#5]
Pretty sure this command used to work, but no longer works.

``` 
$ gngs 'SAM.eachRead { println it.getAttribute("NM") }' < sample.bam 
Caught: java.lang.ClassCastException: script_from_command_line$_run_closure1 cannot be cast to java.io.PrintStream
java.lang.ClassCastException: script_from_command_line$_run_closure1 cannot be cast to java.io.PrintStream
	at script_from_command_line$_run_closure1.doCall(script_from_command_line:4)
	at gngs.SAM.eachRead(SAM.groovy:1323)
	at gngs.SAM$eachRead.call(Unknown Source)
	at script_from_command_line.run(script_from_command_line:4)
```

**Comment by ssadedin** [comment]
Just gave it a  quick test and seems like it's working for me.

It looks a bit like the kind of error I see when GNGS gets used with a different version of groovy to what it was compiled with. See what you get from `groovy -version` and then build with 

```
./gradlew -P GROOVY_VERSION=<your version> clean jar
```

For example,

```
./gradlew -P GROOVY_VERSION=2.4.10 jar
```

Let me know if that doesn't help!

**Comment by averagehat** [comment]
I think this should be added to the instructions--I have hit this twice on separate linux machines after following the SDK MAN instructions

**Comment by ssadedin** [comment]
thanks for mentioning - will add this to the main README.
